web/fang/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/',views.index,name='index'),
        #path('city/<int:id>/',views.city),
    path('area/<int:city_id>/<int:area_id>/<int:page_num>/',views.area),
    path('tu/',views.tu),
    path('deal/',views.deal),
]

web/fang/fang/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include(("app.urls",'app'),namespace='app')),
]

web/fang/app/models.py
from django.db import models

# Create your models here.

class Province_table(models.Model):
    province_name=models.CharField(max_length=20)
    class Meta:
        db_table="province_table"

class  City_table(models.Model):
    province_table=models.ForeignKey(Province_table,on_delete=models.CASCADE)
    city_name=models.CharField(max_length=100)
    city_url=models.CharField(max_length=500)
    class Meta:
        db_table="city_table"

class TypeOfHouse_table(models.Model):
    city_table=models.ForeignKey(City_table,on_delete=models.CASCADE)
    house_type=models.CharField(max_length=100)
    house_url=models.CharField(max_length=500)
    class Meta:
        db_table="typeofhouse_table"

class Area_table(models.Model):
    typeofhouse_table=models.ForeignKey(TypeOfHouse_table,on_delete=models.CASCADE)
    area_name=models.CharField(max_length=100)
    area_url=models.CharField(max_length=500)
    class Meta:
        db_table="area_table"


class NewHouseInfo_table(models.Model):
    area_table=models.ForeignKey(Area_table, on_delete=models.CASCADE)
    house_image=models.CharField(max_length=500)
    house_detail=models.CharField(max_length=200)
    house_name=models.CharField(max_length=100)
    house_descript=models.CharField(max_length=200)
    house_size=models.CharField(max_length=100)
    house_address=models.CharField(max_length=100)
    house_phone=models.CharField(max_length=500)
    house_price=models.CharField(max_length=50,default='0')
    house_label=models.CharField(max_length=200,default='无')
    class Meta:
        db_table="newhouseinfo_table"

web/fang/app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
# Create your views here.
from django.http import HttpResponse
from .models import NewHouseInfo_table,Province_table,City_table,TypeOfHouse_table
import requests
from django.core.paginator import Paginator
# def city(request,id):
#     city=TypeOfHouse_table.objects.filter(id=id)[0]
#     context={
#         'city':city,
#     }
#     return render(request,'app/city.html',context)
#from django import template
#register=template.Library()
#@register.filter
#def to_and(value):
#    return value.replace("/")
def area(request,city_id,area_id,page_num):     #
    result = NewHouseInfo_table.objects.filter(area_table_id=area_id)
    city = TypeOfHouse_table.objects.filter(id=city_id)[0]
    p=Paginator(result,10)
    if p.num_pages<=page_num:
        page1 = p.page(p.num_pages).object_list
    else:
        page1=p.page(page_num).object_list
    for i in page1:
        i.label=(i.house_label).split("/")
    context={
        "results":page1,
        'next':page_num+1,
        'last':page_num-1,
        'city_id':city_id,
        'area_id':area_id,
        'city': city,
    }
    return render(request,"app/area.html",context)
def index(request):
    provinces=Province_table.objects.all()
    context={
        "provinces":provinces,
    }
    return render(request,"app/home.html",context)

    # # header = {
    # #     'refer': 'https://www.baidu.com',
    # #     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    # # }
    # # date=requests.get(url,header=header)
    # # for i in result[]
    # result=NewHouseInfo_table.objects.filter(Area_table_id=2)
    #
    # context={
    #     "results":result[:10],
    # }
    # return render(request,"app/index.html",context)

def tu(request):
    return render(request,'3.html')

import json
def deal(request):
    x=request.GET['x']
    y=request.GET['y']
    url="http://api.map.baidu.com/place/v2/search?query=%E5%B0%8F%E5%8C%BA&location="+str(y)+","+str(x)+"&radius=2000&output=json&ak=CzyN8k3YK9BVpP2fOwhtiCpkkZKwASd5"
    data=requests.get(url)
    data=data.json()
    #x=data['results'][0]['location']['lat']
    #y=data['results'][0]['location']['lng']
    #data={}
    #data['x']=x
    #data['y']=y
    result="<ul>"
    for name in data['results']:
        result=result+"<li><a>"+name['name']+"</a><li>"
    result=result+"</ul>"
    return HttpResponse(result)

web/fang/templates/3.html
<!DOCTYPE html>  
<html>
<head>  
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />  
    <meta http-equiv="Content-Type" content="textml; charset=utf-8" />  
      
    <style type="text/css">  
        html{height:100%}  
        body{height:100%;margin:0px;padding:0px}  
        #container{height:100%;width: 80%;float: left;}
        ul{
            list-style:none;
        }
        li{
            color:red;
        }
    </style>  
    
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=3.0&ak=CzyN8k3YK9BVpP2fOwhtiCpkkZKwASd5"></script>
</head>  
 
<body>
	<div id="container"></div> 
	<div style="height: 100%;float: left;width:17%;">
		<h2 style="text-align:center;">推荐</h2>
		<p id="p"></p>
	</div>
</body> 
<ml>
<script type="text/javascript">
	var map = new BMap.Map("container");// 创建Map实例
	var mPoint = new BMap.Point(116.404, 39.915);  
	map.centerAndZoom(mPoint,15);  //初始化地图
	
	map.enableScrollWheelZoom();  //支持地图缩放
	
	//根据浏览器定位
	var geolocation = new BMap.Geolocation();
	geolocation.getCurrentPosition(function(r){
		if(this.getStatus() == BMAP_STATUS_SUCCESS){
			var mk = new BMap.Marker(r.point);
			map.addOverlay(mk);
			map.panTo(r.point);
			alert('your location :'+r.point.lng+','+r.point.lat);
		}
		else {
			alert('failed'+this.getStatus());
		}        
	},{enableHighAccuracy: true})
	
	
	//地图选点获取经纬度
	map.addEventListener("click",function(e){
		
    		var point = new BMap.Point(e.point.lng, e.point.lat);  
    		var circle = new BMap.Circle(point,1000,{fillColor:"blue", strokeWeight: 1 ,fillOpacity: 0.3, strokeOpacity: 0.3});
    		map.addOverlay(circle);
			loadXMLDoc(e.point.lng,e.point.lat)
		var local =  new BMap.LocalSearch(map, {renderOptions: {map: map, autoViewport: false}});  
    		local.searchNearby('小区',point,1000);
    		
	});

	function loadXMLDoc(x,y)
{
	var xmlhttp;
	if (window.XMLHttpRequest)
	{
		// IE7+, Firefox, Chrome, Opera, Safari 浏览器执行代码
		xmlhttp=new XMLHttpRequest();
	}
	else
	{
		// IE6, IE5 浏览器执行代码
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			document.getElementById("myDiv").innerHTML=xmlhttp.responseText;
		}
	}
	xmlhttp.open("GET","/app/deal/?x="+x+"&y="+y,true);
	xmlhttp.send();

	xmlhttp.onreadystatechange=function()
  {
    if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
		document.getElementById("p").innerHTML=xmlhttp.responseText;
    }
  }
}
</script>

web/fang/templates/4.html
<!DOCTYPE html>  
<html>
<head>  
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />  
    <meta http-equiv="Content-Type" content="textml; charset=utf-8" />  
      
    <style type="text/css">  
        html{height:100%}  
        body{height:100%;margin:0px;padding:0px}  
        #container{height:100%;width: 80%;float: left;}

    </style>  
    
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=3.0&ak=CzyN8k3YK9BVpP2fOwhtiCpkkZKwASd5"></script>
</head>  
 
<body>
	<div id="container"></div> 
	<div style="height: 100%;float: left;width:17%;">
		<h2>推荐</h2>
		<p id="p"></p>
	</div>
</body> 
<ml>
<script type="text/javascript">
	var map = new BMap.Map("container");// 创建Map实例
	var mPoint = new BMap.Point(116.404, 39.915);  
	map.centerAndZoom(mPoint,15);  //初始化地图
	
	map.enableScrollWheelZoom();  //支持地图缩放
	
	//根据浏览器定位
	var geolocation = new BMap.Geolocation();
	geolocation.getCurrentPosition(function(r){
		if(this.getStatus() == BMAP_STATUS_SUCCESS){
			var mk = new BMap.Marker(r.point);
			map.addOverlay(mk);
			map.panTo(r.point);
			alert('your location :'+r.point.lng+','+r.point.lat);
		}
		else {
			alert('failed'+this.getStatus());
		}        
	},{enableHighAccuracy: true})
	
	
	//地图选点获取经纬度
	map.addEventListener("click",function(e){
		
    		var point = new BMap.Point(e.point.lng, e.point.lat);  
    		var circle = new BMap.Circle(point,1000,{fillColor:"blue", strokeWeight: 1 ,fillOpacity: 0.3, strokeOpacity: 0.3});
    		map.addOverlay(circle);
			loadXMLDoc(e.point.lng,e.point.lat)
		var local =  new BMap.LocalSearch(map, {renderOptions: {map: map, autoViewport: false}});  
    		local.searchNearby('小区',point,1000);
    		
	});

	function loadXMLDoc(x,y)
{
	var xmlhttp;
	if (window.XMLHttpRequest)
	{
		// IE7+, Firefox, Chrome, Opera, Safari 浏览器执行代码
		xmlhttp=new XMLHttpRequest();
	}
	else
	{
		// IE6, IE5 浏览器执行代码
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			document.getElementById("myDiv").innerHTML=xmlhttp.responseText;
		}
	}
	xmlhttp.open("GET","/app/deal/?x="+x+"&y="+y,true);
	xmlhttp.send();

	xmlhttp.onreadystatechange=function()
  {
    if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
		alert('a');
        data=mlhttp.responseText;
        alert(data);
    }
  }
}
</script>

web/fang/templates/app/area.html
{% extends "base.html" %}
{% load static %}
{% load to_and %}
{% block link %}
<style>
    #aa{
     font-size:12px;
     border:1px rgb(221, 221, 221) solid;
     padding:2px;
     color:rgb(153, 153, 153);
    }
    #aa:hover{
        color:red;
        border:1px red solid;
    }
    a{
        text-decoration : none;
    }
    .blo:hover{
        background-color:rgb(245,245,245);
    }
</style>

{% endblock %}

{% block content %}
<br>
<div class="container">
        <p style="text-align:center;border-bottom:1px grey solid;"><strong >{{city.house_type}}</strong></p>
            <ul style="list-style-type: none;margin:0px;padding:0px;">
                {% for area in city.area_table_set.all %}
                    <li style="display:inline-block; padding:5px;"><a class="btn btn-default" href="/app/area/{{city_id}}/{{area.id}}/1">{{area.area_name}}</a></li>
                {% endfor %}
             <a href="/app/tu/" class="btn btn-primary">地图选房</a>
            </ul>
    
    <div class="container col-xs-8">




        {% for result in results %}
        <div style="border-bottom:1px rgb(200,200,200) solid;" class="row blo">
            <br>
            <br>
            <div style="height:80px;width:200px;" class="col-xs-2">
                <a href="{{result.house_detail}}"><img src="{% static 'image/aa.jpg' %}"></a>
            </div>
            <div style="height:80px;" class= "col-xs-5">
                <strong><p>{{ result.house_name }}</p></strong>
                <p style="color: #999;font-size:12px;">{{ result.house_descript }}&nbsp;~&nbsp;{{ result.house_size }}</p>
                <p style="color: #999;font-size:12px;">{{ result.house_address }}</p>
                {% for label in result.house_label|to_and %}
                    <a href="" id="aa">{{label}}</a>&nbsp;
                {% endfor %}
                <!--<a href="" id="aa">在售</a>&nbsp;<a id="aa" href="">普通住宅</a>&nbsp;<a href="" id="aa">品牌产品</a>-->
            </div>
            <div class='col-xs-offset-9' style='height:80px;padding:0px;'>
                <p style='color:red;font-size:20px;font-weight:bold;margin:0px;'> 价格：{{ result.house_price }}</p>
                <br>
                <p style='color:black;font-size:15px;font-weight:bold;margin:0px;'>电话：{{result.house_phone}}</p>
            </div>
            <br><br><br>
        </div>
        {% endfor %}
        <ul class="pager">
            <li><a href="/app/area/{{city_id}}/{{area_id}}/{{last}}">Previous</a></li>
            <li><a href="/app/area/{{city_id}}/{{area_id}}/{{next}}">Next</a></li>
        </ul>

    </div>

    <script>
        data = {
            labels: ["最高价格", "平均价格", "价格"],
            datasets: [
                { values: [120000,90000,100000] }
            ]
        }

        new frappe.Chart( "#chart", {
            data: data,
            type: 'bar',
            height: 180,
            colors: ['red']
        });
    </script>
</div>

{% endblock %}

web/fang/templates/app/city.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>城市</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        {{city.house_type}}
        <a href="">不限</a>
        {% for area in city.area_table_set.all %}
            <a href="/app/area/{{area.id}}/1">{{area.area_name}}</a>
        {% endfor %}
    </div>

</body>
</html>

web/fang/templates/app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .{{area.id}}{
            background-color:red;
        }
    </style>
</head>
<body style="background-color:white;">
    <div class="container">
        {% for province in provinces %}
            <div>
                <strong>{{ province.province_name }}</strong>&nbsp;&nbsp;&nbsp;
                {% for city in province.city_table_set.all %}
                <a href="/app/area/{{city.id}}/1/1/">{{city.city_name}}</a>&nbsp;&nbsp;
                {% endfor %}
            </div>
            <br>
        {% endfor %}
    </div>
</body>
</html>

web/fang/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/frappe-charts@1.2.4/dist/frappe-charts.min.iife.js"></script>
            <!-- or -->
    <script src="https://unpkg.com/frappe-charts@1.2.4/dist/frappe-charts.min.iife.js"></script>
    {% block link %}

    {% endblock %}
</head>
<body>
    {% include "header.html" %}
    {% block content %}

    {% endblock %}
    {% include "footer.html" %}
</body>
</html>

web/fang/templates/header.html
{% block header %}
<!--<div class="container" style="background-color:black;">-->
<!--	<strong style="line-height:50px;color:white;"><a href="/app/index">主页</a> </strong>-->
<!--</div>-->
{% endblock %}